# Generated by Django 3.1.3 on 2020-11-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='MainApp.category'),
            preserve_default=False,
        ),
    ]
